# Generated by Django 5.2.4 on 2025-07-11 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('Average_Rating', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20)),
                ('Isbn13', models.CharField(max_length=20)),
                ('Language_Code', models.CharField(blank=True, max_length=255)),
                ('Num_page', models.PositiveIntegerField(blank=True, null=True)),
                ('Ratings_Count', models.PositiveIntegerField(blank=True, null=True)),
                ('Text_Reviews_Count', models.PositiveIntegerField(blank=True, null=True)),
                ('Publication_Date', models.CharField(blank=True, max_length=220, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('Actions', models.CharField(blank=True, max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('debt', models.CharField(blank=True, default=0, max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('rent_fee', models.CharField(max_length=225)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
            ],
        ),
    ]
